### ISSUE TITLE
I felt the font color of the HTML tags too low contrasted and dark [in dark theme]. Found it quite hard to read. 

### ISSUE THREAD

**Issue by shylaysh** [ofrades/Teppz#1]
Hi there,

I really love your theme "Teppz" and it one of my best themes ever. However, I find it quite hard to read fonts of the html tags as it is too low contrasted and dark colored. So, I request you to make font of html tags quite contrasted and lil bit brighter so that it will be easy to read. 

Thank you!

Regards,
Shailesh 
![Capture](https://user-images.githubusercontent.com/36802984/76286311-e2b9d700-62c9-11ea-94c1-94dd0d27eba5.PNG)

**Comment by ofrades** [comment]
Hello @shylaysh 
Thanks for the nice words, must of the work was done by the creator of eppz.
Have a look a the new release 2.2.4 and tell me what you think.

**Comment by shylaysh** [comment]
Hi Miguel!

Thank you so much for considering my request. Now it looks perfect!!

Regards,
Shailesh Khanal
